name: Check Dependabot PR

permissions: read-all

on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR is from Dependabot
      if: github.event.pull_request.user.login == 'dependabot[bot]'
      run: echo "This PR was created by Dependabot."

    - name: Exit if not Dependabot
      if: github.event.pull_request.user.login != 'dependabot[bot]'
      run: |
        echo "This PR was not created by Dependabot."
        exit 1
