name: Docker Pull with Cache
on:
  workflow_dispatch:  # Manual trigger
  pull_request:

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'hebertpena88'
          password: 'dckr_pat_YYzuHiFJoYJSzEVxi1Ejp4Etw_o'
      - name: Check for cached image
        id: cache-docker-image
        uses: actions/cache@v3
        with:
          path: /tmp/docker-image.tar
          key: docker2-browserless-chrome-${{ hashFiles('.github/workflows/docker-pull.yml') }}

      - name: Pull Docker image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: |
          docker pull browserless/chrome@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f
          docker tag browserless/chrome@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f browserless/chrome:cached
          docker save browserless/chrome:cached > /tmp/docker-image.tar

      - name: Load cached Docker image
        if: steps.cache-docker-image.outputs.cache-hit == 'true'
        run: |
          docker load < /tmp/docker-image.tar
          echo "Using cached Docker image"
          docker images browserless/chrome:cached

      - name: Verify Docker image
        run: |
          docker images
          echo "Successfully pulled/loaded browserless/chrome image"
