name: Docker Pull with Cache

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Weekly run on Sundays at midnight UTC

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'hebertpena88'
          password: 'dckr_pat_YYzuHiFJoYJSzEVxi1Ejp4Etw_o'
      - name: Setup Docker Layer Caching
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-browserless-chrome
          
      - name: Pull Docker image
        run: |
          docker pull browserless/chrome@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f
          docker tag browserless/chrome@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f browserless/chrome:latest

      - name: Save Docker image
        run: |
          docker save --output ~/.docker-images.tar browserless/chrome:latest
